#+SETUPFILE: ../setup.org
#+FILETAGS: blog
#+TITLE: 怎么弄个自己的 blog
#+DATE: [2022-10-10 Mon 23:55]

#+ATTR_HTML: :class top-down-img
[[https://www.pixiv.net/artworks/83290347][file:0.jpg]]

大概是在三年前，我在 CSDN 上发了自己写的第一篇博文，不过读者寥寥，到现在也才两三百的阅读量。二〇年上半年疫情期间，我试着在 godaddy 上使用 wordpress 创建了一个博客，然后写了一些博文，大部分应该在知乎同步发了。接着在二一年下半年我放弃了 wordpress，转而使用 emacs 的 org-mode 来通过 org 文档创建 html 页面，靠着几乎裸露的 html 和拿过来的 css 勉强糊了个个人博客。现在，是时候做个自己完全可控的 blog 出来了。

和我先前写过的 emacs 系列（还没写完就是了）的第一篇一样，本文并不包含太多有用的内容，而是一系列文章的头一篇，用来说明接下来文章的内容和用途。相比于离结束遥遥无期的 emacs 系列，在试用过市面上主流或小巧的博客系统或文档发布系统后，我会以一个基于 emacs 的博客系统作为这一系列的结尾。预计这一系列的文章总数不会超过十几篇，毕竟我也想早日用上自己的写的博客系统。和网页相关的东西不可避免的会涉及到 HTML+CSS+JS 三剑客，不说熟练于心我现在至少知道它们的简单用法了，不会写我还不会抄吗（笑）。

本文包括的内容如下：

- 为什么要写博客
- 为什么要弄自己的博客系统
- 你能从这一系列中学到什么
- 接下来的工作

* 为什么要写博客

如果你看的博客够多，那些存活时间比较长的博客中大都会对这个问题做出过回答。所谓“一千个读者心中有一千个哈姆莱特”，这里我也没必要参考他人的观点，而是直接给出我自己的想法：我写博客就是为了记笔记，顺带发出来。我的第一篇博文就是解一道物理题：两间距 1m 且质量 1kg 的小球仅在引力作用下用时多久接触？答案是大约 26.7 小时，顺便我还得到了副产物：

\[\int_{}{}\frac{1}{ch^{n}\theta}d\theta = \frac{1}{n-1}(\frac{sh\theta}{ch^{n-1}\theta}+(n-2)\int_{}{}\frac{1}{ch^{n-2}\theta}d\theta) \quad n\geq 3\]

文本形式的 latex 代码并不适合阅读，生成 pdf 的话不像网页那样便于阅读，所以我选择将笔记以网页的形式呈现。光是笔记的话并不一定对每一个人来说都容易读懂，所以要发布的话需要对笔记文本进行一定的修改和润色。这大约就是我写博客的具体过程，首先学个新东西，觉得有点价值就记下来，其他人没有发过或者我觉得很有意思的东西就修改了发出来。

某种意义上来说我这也算是一种自娱自乐行为，毕竟我不指望像 [[https://beautifulracket.com/appendix/racketcon.html#a_0ZQ03][beautiful racket]] 一样靠 blog 或出书赚钱。

* 为什么要弄自己的博客系统

博客系统这个词可能稍微大了些，我想表达的意思就是一个用于管理博文的软件，它应该包括一系列通常博客应该具有的功能（但是具体包括哪些我现在还不是很清楚，这些将在随后的文章中解决）。之所以要自己写博客管理软件是出于两个原因，一是仓鼠心态，如果一些流行的博客软件不再维护了，而且我也没有能力进行修改的话那就木大了，趁现在有时间和精力自己写一个，留下一些足够详细的文档，可能抗风险能力更强一些；二是现在的一些博客软件在我看来太庞大了一些，很多的功能我都不是很需要，自己写的话可以仅实现自己想要的功能，没有洁癖带来的心理负担。

当然上面两个原因听起来确实挺滑稽的，我毫不怀疑一些软件活得时间比我还长，而且软件不再频繁维护可能并不是因为软件死掉了，而是软件的功能已经稳定下来了，而且基本感觉不到 bug 了。至于第二个原因，我只需要当其他功能不存在就行，心中无码自然高清。

所以，为什么要弄自己的博客系统，当然是我想弄自己的博客系统。

* 你能从这一系列中学到什么

大体来说这一系列文章就是我自娱自乐的产物，但我也不会弄成写给我自己看的晦涩笔记。对于折腾过的软件，我会给出详细的安装和使用方法，如果已有较好的教程我也会给出来源。对于一些一般性的知识，我会尽可能给出准确来源，并用我自己的语言给出尽量易懂的描述。对于出现的代码，我尽量保证在给定环境下能够正常执行并得出正确结果。

总的来说就是折腾各类博客软件的过程总结。如果你也折腾的话也许能做点简单的参考。

* 接下来的工作

这一系列文章描述的是我在不断尝试不同博客软件过程中不断积累经验和知识，最后编写自己的博客软件的一个过程。大致会包括这些内容：

- 折腾各种博客软件的过程
- 引用转载的规范问题
- 对 CC 协议的认识
- 一些比较不错的博客介绍

是的，除了博客软件外，我还会学习一些常见的知识产权和著作权知识，不管怎么说博文也算一种作品。

以上。在这一系列完成后我会将所有文章的链接贴在下面。
