#+SETUPFILE: ../../setup.org
#+FILETAGS: gossip

#+TITLE: 对知识和认知的思考
#+DATE: [2023-02-10 Fri 16:54]

这是一个我在很久之前就想写的话题了，但是由于水平和知识不够一直都不知到从何下笔。年初我偶然发现了一本叫做 /[[https://yueyao1982.com/reconstr_phil/index.html][哲学的重建]]/ 的书，虽说不是全都能看懂但也了解了个大概，整个一月份我也零零散散在网上找了些跟标题话题相关的资料。虽说现在不一定能写完，但是我感觉已经可以开始写了，就拿他作为新博客的第一篇开始写的文章吧。

本文的重点不在“如何做”上，比如怎么学习或者怎么整理。我写这篇文章的主要目的是尝试解决过去我的一些疑惑。就个人具体应该怎么做，也许后续我会继续写上几篇文章。

* 为什么要写这篇文章

自从我拥有属于自己的手机后，我就感觉很少有过长时间的思考了。与纸质媒体时代相比，数字媒体在传播能力和信息总量上完成了碾压，只需要点点鼠标或者划划屏幕我们就能够以纸媒时代想都不敢想的效率和便利访问世界各地的最新讯息。

看起来这事百利无一害是吧，但我也隐隐约约有种被网络控制的感觉，有时候能顺着短视频下拉刷上几个小时，做东西做不下去时就开始乱翻网页，看到比较长的文章直接点赞留个印记之后再读，由于看手机熬夜导致的注意力严重下降，某个东西想着想着就忘了上一刻在想什么，等等。不知读者是否看过《百年孤独》，我现在的状态可能和马孔多里的失眠症差不多：

#+BEGIN_QUOTE
“咱们永远不可睡觉吗？那就更好啦，”霍·阿·布恩蒂亚满意他说。“咱们可从生活中得到更多的东西。”可是印第安女人说明：患了这种失眠症，最可怕的不是睡不着觉，因为身体不会感到疲乏；最糟糕的是失眠症必然演变成健忘症。她的意思是说，病人经常处于失眠状态，开头会忘掉童年时代的事儿，然后会忘记东西的名称和用途，最后再也认不得别人，甚至意识不到自己的存在，失去了跟往日的一切联系，陷入一种白痴似的状态。霍·阿·布恩蒂亚哈哈大笑，差点儿没有笑死，他得出结论说，迷信的印第安人捏造了无数的疾病,这就是其中的一种。

他用小刷子蘸了墨水，给房里每件东西都写上名称：“桌”、“钟”、“们”、“墙”、“床”、“锅”。然后到畜栏和田地里去，也给牲畜、家禽和植物标上名字：“牛”、“山羊”、“猪”、“鸡”、“木薯”、“香蕉”。人们研究各种健忘的事物时逐渐明白，他们即使根据签条记起了东西的名称，有朝一日也会想不起它的用途。
#+END_QUOTE

考虑到这现实中的“健忘症”还没有达到失去一切联系的阶段，拿小刷子给东西写上名字也是一种不错的对抗手段。大概是自疫情开始我就有了记点东西的习惯，写到现在也有小几十篇了。就我个人体验来说，这一段时间以来唯一让我进入所谓“心流”状态的时候就是写东西的时候，打字将我的注意力重新拉回到思考上，而不会被网页或者噪声干扰。从疫情到现在也差不多有三年了，如果说在这段不断往下走的时间中有什么收获的话，那大概就是重新找到了这一集中注意力的方法（笑）。

如果说反抗一个东西的开始是认识到这个东西的存在的话，那么本文就可以看作是我的开始罢，这也就是本文对我的意义。说是反抗可能有点夸张了，更准确的说法是开始动脑子认识一下自己的现状和所面对的东西了。

#+BEGIN_QUOTE
互联网就是一堆未经把门的谣言、流言与谎的集合。它把我们的注意力切割成碎片，终结了那些长线的深入的思考。我们的孩子，再也不读书了。他们当然更不读报纸了。人人都能在网络上找到一个大扩声器，发出和受过良好教育及训练的人一样高扬的声音，哪怕他的观点再愚不可及。我们在网络上建了一个“回声室”，而且实际上，挑战我们想法的人，竟然比之前的广播时代还要少。谷歌正在腐蚀我们的记忆力，它让我们变蠢。网络钟爱狂热的、偶像导向的业余者，让专业人士丢掉了饭碗。网络代表了粗鄙者的崛起，剽窃者的胜利，文化的终结，一个黑暗时代的开始。这个时代的主人是那些满目呆滞的习惯性的自慰者，在他们眼里，多数人同意的即是真理，各种观点的大杂烩即是智慧，人们最乐于相信的即是知识。

然而同时，也有一些诸如 Politifact.com 这样的网站，在认真核查新闻媒体报道的事实，甚至比之前任何⼀个时代都更仔细、更公开。《纽约时报》的记者乔迪·坎托（Jody Kantor）说，知道博主们会仔细阅读她写的每⼀个字后，她对工作更加精益求精了。图书馆也在进行新的尝试，利用所有可得的数据——包括读者们提供的数据——从而使得读者们在查找所需资源时比以前省事多了。得益于那些新的协作式技术，以及海量数据发布的新方式，科学也在以前所未闻的速度发展着。至于商界，更是进入了⼀个管理的新时代，通过从自己的组织的各个角落、从与组织相关的各色人等当中去发现专业人才而颠覆预期。

所以，我们既面临知识的危机，然而同时，也面临着⼀场划时代的知识的提升。一方面我们为曾经深深依赖、给我们提供可信知识的机构而担忧；另一方面，我们也能感到一种文化脉动的喜悦。这种喜悦来自⼀个完全不同的地方。它来自于知识的网络化（the networking of the knowledge）。知识现在不仅仅存在于图书馆、博物馆和学术期刊里。它不仅仅存在于个人的大脑里。我们的大脑、我们的机构，都根本不足以装下足够多的知识。知识现在具有了网络的属性，这网络，存在于商业、政府、媒体、博物馆、图书馆，以及人们沟通时的想法中。

《知识的边界》 —— 戴维•温伯格 （ /Too Big to Know/ -- David Weinberger）
#+END_QUOTE

《知识的边界》这本书的出版时间是 2012 年，中译版由山西人民出版社在 2014 年出版，不管是原版还是中文版到现在都差不多有 10 年了，当时的我还在读初中，对电脑和网络的认识也就是 CS online 和 LOL。现在相比于 10 年前的变化也是不少，但这本书还是挺值得一看的。


