#+TITLE: 既然决定要活下去，我就必须工作
#+DATE: [2024-12-28 00:12]
#+AUTHOR: ???

#+begin: note
不知道从哪里找到的小说...
# cmVhZC5waHA/dGlkPTIzMTU2MDU=
#+end:

既然决定要活下去，我就必须工作，赚取填饱肚子的钱。

新年过后，带着仍未完全调整过来的情绪，我开始求职。

首先，我阅览便利店买的求职杂志以及网上的招聘广告，寻找符合条件的工作。我还是希望能找电脑相关的白领职位，但这类招收似乎不如过去那么多了。

是单纯一月这个时间点不好呢？还是盛极一时的网络热潮在渐渐衰退？我不清楚原因，可要是招收量减少，竞争率升高，对于没有任何技术专长的我来说，形势并不乐观。餐厅和便利店的工作依旧很多，但事到如今，找这种干不长久的零工是没有意义的。既然已经决心真正步入社会，且不论雇佣形态，至少工作内容要值得写进简历才行。

总之先在劳务派遣公司之类的地方登记吧。我打电话咨询，被要求接受一个简单的测试。

当天，我提前了一些出门。铅灰色的天空十分阴沉，路上的行人都把脸颊藏在围巾或竖起来的衣领中。我原以为已经穿足了衣服，但依然寒冷难耐。快步走在柏油路上，时隔良久，膝盖又因为走路微微痛了起来。

坐电车十分钟左右，我到达了目的车站，劳务派遣公司位于车站近旁的楼房内。电梯里灯光昏暗，氛围不是很好。

接应我的是位年轻男子，身穿没有一丝褶皱的西装。他虽然言谈彬彬有礼，却不苟言笑，说明方式也极其冷淡，语速很快，整体上给我无礼的印象。派遣公司对待来登记的人都是这副态度吗？还是说只是这个员工的素质问题？我不太明白。毕竟，无论担任交涉工作的人是冷漠还是反之太过热情，都说明这家企业有问题——过去维修机器时走访公司的经验使我提起警惕。

交完简历，我被带到了一个和车站厕所单间差不多的狭小房间。我脱下外套，屋里的暖气似乎没有运作，我又立即穿上。

好久没有进行笔试了。上大学期间，我打从心底觉得学分拿不拿都无所谓，所以要说真的具有衡量意义的测验，恐怕得追溯到大学入学考试了。

真的没问题吗？我不光有一段空白期，脑细胞也因药物滥用的疯狂生活而灭绝，毫无自信可言。我做好了一定思想准备，然而印在卷子上的问题并不是很难。

这下即便是现在的我也能轻松回答。安心的同时我拿起铅笔，正准备填写姓名时，我惊呆了。

我的手指不住地颤抖，无法将笔画写直。

难道是气温比我所感觉的更冷，手指冻僵了吗？我放下铅笔，揉搓双手，向手指哈气，然后重新握笔。颤抖虽然平息了，指尖却仍有些不对劲。

我写不出正常的字。虽说我的字本来就不好看，但与以前的水平相比，这字太过拙劣，简直像刚学会写字的幼儿笔下的东西，纯粹是在画线。即使我反复擦掉重写，出现在纸上的依然是同样扭曲的文字。看着它们，我感觉像是在做一场噩梦。

我一次次放松、暖热指尖，文字却丝毫没有改善，依然不堪入目。也就是说原因不在身体上。莫非我是在紧张吗？可是至今以来，无论在什么地方，接受什么考试，我都完全没有紧张过。

我卡在第一道题上，一次次地擦了又写。负责人投来了冰冷的视线，看他的表情，似乎是在想：“这才刚开始，他在干什么”、“来了个无能的家伙”。啊，我明明知道答案！水准这么低的考试，竟让他如此嚣张。不管字好不好看，时间都在分分秒秒地流逝。我用这拙劣至极的文字填入了答题栏。

在最后关头，我总算完成了全部问题。累得我精疲力竭。正确率应该不会太低，但不知道阅卷人能否读懂我的字。就算能读懂，他们会聘用书写这么烂的人吗？

“接下来请到这边的房间。”

没有休息的时间，我移动到另一个房间进行盲打速度测试。给我的是一台老旧的Windows电脑，已经启动了测试程序。

这位男子为我说明了操作方式。据他所说，这套软件有着独特的汉字变换方式，似乎是基于微软日文输入法。平时使用ATOK158的我不习惯这种操作方式，但也不是完全没用过。

我打字速度还算快，想要在这一项上挽回刚才丢掉的分数。要是拿到好成绩，指不定能拿到电脑操作员的工作。

然而，打字同样失败了，手指依然无法正常运动。此外，和平时不同的变换方式也使我反应不过来。失误，删除，如此反复。

到底是怎么回事啊？这点小小的变动，我不是总能现场适应吗？对这方面的能力我是有相当自信的，可为什么如此简单的事我都做不到呢？

我带着陷入泥潭般的心情输入完，考试结束。结果虽然不公开，想必糟透了。

不出所料，无论等多久，劳务派遣公司都没有发来工作介绍的消息。

在此期间我也没有闲着，通过求职杂志的信息接受了几回面试，但要么是谈过发现宣传与内容不符，要么是被对方拒绝，很长时间都没有找到工作。

拒绝原因并非必备技能的水准要求过高、我无法胜任。有时也会有“你会安装操作系统吗？”这种极为初级的提问，可就连这样的公司也没录用我。

无论去哪里面试，总能见到几名身穿西服的年轻人在排队。果然，如我看求职信息时所预料的那样，这个行业不再是过去那个卖方市场，已经有人开始失业了。对我这种各方面都是半吊子的人而言，可钻的空子已经不多。

就这样，二月告终，三月临近时，我依然无法找到工作。正在这时，我受邀去阿叠家和大伙一起聚会，便久违地出了一趟远门。

乘坐中央线的红色电车在荻洼站下车，打了通电话，阿叠很快就来接我了。真赤家中那件事过后已有一段时间，我和他的关系恢复如初。我们到车站旁的餐厅吃饭，我点了啤酒和炖带籽鲽鱼套餐，阿叠挑了盐烤秋刀鱼套餐。

他所住的公寓就在走路十分钟开外的地方。一摸栏杆，上面生着铁锈。建筑陈旧，关上门也会有风从缝隙透入，但面积有两室一厅一厨，居住的感觉应该不坏。

那天要来的有鸳野、宇见户、以及一位正在经营插画网站的学生，叫做川喜田。等人到齐的期间，我和阿叠聊起天。

我陷于找不到工作的困境，而阿叠也在经济危机中挣扎。

“眼下还能养活自己，但如果考虑将来，自由职业程序员是当不长久的。新技术不断涌现，上了年纪迟早会应付不来。如果待在组织里，还能靠从事管理职位苟且，可自由人终究是一次性的，用完就丢弃。”

他说自己正在摸索别的职业出路，但暂时还没有眉目。

刚搬进花园公馆的时候，我和阿叠每天都聊天。真赤到来之后，谈话减少了。而如今我们分开居住，连见面说话的机会都不多。所以，如今像过去一样聊着天，我感到些许怀念。

各自汇报完阴沉的近况，我们谈起共同的熟人，说到了当下引发一时热议的草野。

他断绝了音信，去向不明。

我和别人已经很少交流，完全和这些消息疏远。尽管如此，我还是听到了传闻：这个长着平脸的男子数月前辞职了，之后一直没有固定职业，靠向恋人、朋友借钱度日。而他突然间失去了联系，从住处消失了。

“几个跟他关系近的人打过电话，他只接了一次，之后再怎么打也打不通了。”阿叠说道。

“是不是回老家了？我记得他好像是外地出身。”

“没有，老家他也没回。他父母也不知道草野目前住在哪里，还找认识草野的人问呢。”

“那可真不得了。也就是说，之前在井之头公园见面的时候，他就已经负债累累了？”我问道。

“嗯，应该是。”

“完全看不出来啊。到底发生什么了？草野明明不是会这么胡来的人。”

“估计是精神错乱了吧。”阿叠回答。

“给他借钱的人呢？”

“当时很愤怒，现在已经平息了。”

“为什么？”

“他父母全额支付了呀。他们找到草野乡下的父母，说草野失踪了，让他们很为难。”阿叠笑道。

“真过分。”我也笑了。

“怎么还没有人到。对了，水屋口，要叫人来吗？”

“叫人？谁？”

“之前东先生带了一个女人，有一半白人血统，不过和咱们想象中的混血儿不同。”

“怎么不同？”

“感觉像个摔角手一样，特别积极，还给我留了电话号码。叫的话说不定她现在就会赶来。怎么样？叫吗？”

“不，免了吧。”我皱起眉头。

“也是。说实在的，她来了我也头疼。”阿叠又笑了。

接着，我们说起了某个著名网站男站主的坏话，又谈到了最近刚确认自杀的女站主。

之后，在我们聊的期间，宇见户来了。没多久，从另一场线下会出来的鸳野以及和她关系很近、名叫川喜田的人也到了。于是，我们一边吃着从便利店买来的饭菜，一边聊了许多没有营养的话题。

宇见户打算利用在“RM”中建立的文本网站界人脉举办另一种活动。不同于以往类似线下会的派对，这类活动表演性更强，要从观众身上捞钱。相比于之前的“RM”，这样的活动似乎才是宇见户原本想开展的。他两眼放光，向我们阐述构想。

鸳野在中央线沿线的地方独自生活，万万想不到她成了办公室白领。她这么马虎的人，竟然身穿制服在干净整洁的大楼里工作，究竟是耍了什么花招？她说是网上的熟人介绍的。用不了几天肯定就会辞职吧——我们调侃道，可她反感地说自己工作非常认真。

川喜田是学生，所以在座的当中，我是唯一没有承担任何社会职责的人。意识到这一点，我觉得只有自己低人一等，始终没有心情主动开口。

接着，我们又谈天说地，而后聊到了真赤的事。

“增冈是不是对花园公馆的人都特别嫌弃啊？她好像把咱们统称为‘那个花园的家伙们’，说些坏话。”阿叠说道。

“为什么呀。大家都已经不住在一起了，又没有像小圈子一样行动。”鸳野叹了一口气。

“可能还是因为给她留下了非常糟糕的回忆吧。仔细想想，她过的生活实在太恶劣了。像她这样的年轻女孩，不愿再次回想是很正常的。”说着，阿叠笑了。

“啊，说起来在之前的线下会上，增冈也躲着我。这么说她把我和大家归为一类了？”川喜田插嘴。

“那只是她讨厌你吧。”宇见户一本正经地指出，川喜田露出不悦的表情。

“话说回来，水屋口哥和真赤还有联系吗？”鸳野问道。

“不，完全没有。”我摇头回答。

“哎，看她现在还在网上玩得开心，这样就好。”

阿叠似乎聊腻了，把吉他架在膝上弹了起来。

关于真赤，我并非没有任何想法，但以我们如今的关系，这些话不应在此谈及。说到底，我根本不知道该怎么开口。宇见户和川喜田似乎对我有几分体谅。他们经常在线下会之类的场合和真赤见面，却闭口不提她在其中的不良品行。可连我都听说了传闻，她的行为极其过分。

不经意间，我们陷入了沉默。

“真赤是个小骗人精呀。”鸳野低着头嘟哝。

“怎么了？突然这么说。”我问道。

“那个……我在去花园公馆之前，听真赤说你们欺负她。”说着，她露出苦涩的表情。

“我和水屋口欺负她？”阿叠停下了弹吉他的手，目瞪口呆。

“嗯，她说自己遭受了很恶劣的对待。所以，我最初是满心想要拯救她才搬的家。实际去了之后发现情况完全不对，反倒是大家被真赤摆弄得团团转，不是吗？男人堆里唯一的女孩，像个小公主一样。所以我才那么吃惊……”鸳野耸了耸肩。

这番话使我想起鸳野刚到花园公馆的那天晚上，她边哭边用菜刀割腕的事情。

当时鸳野的解释是真赤因为吸烟问题在背后说她的坏话，让她深受打击。不过，如果她刚刚说的是事实，或许她当时割腕的理由就不止如此，听到的情况和现实截然不同也是原因之一吧。

除此之外，我还想起去京都旅行的时候，真赤直到最后关头才告诉鸳野同行人还有我。本以为是真赤又像平时一样出了差错，倘若是她撒了谎，多少就能解释得通了。和欺负自己的罪魁祸首一起两人旅行，这确实很不自然。

可是，再怎么说她也不至于撒这样的谎吧？不，从一开始我对真赤的这方面性格就抱持宽容的态度，所以我既不为此生气，也没有十分惊讶。我并非不相信鸳野，只是对真赤会说立马就将暴露的谎言感到不可思议。

接着，在又一次降临的沉默之中，鸳野说起了她去真赤老家时的事。

真赤曾透露自己常受双亲虐待，也告诉过鸳野，比如被关在房间里不能出去，等等。然而，当她实际造访真赤家，才发现那里并没有禁闭锁之类的装置，不过是间平凡无奇的住宅。

真赤的父母也比想象之中要正常得多。看他们和真赤说话的样子，根本无法想象此前听说的特殊关系。

“这件事你以前也提到过。”我说道。

“嗯。”鸳野叹了一口气：“……当时还想找她好好谈一谈，最后我被她深恶痛绝……”

她再次为没能让真赤完全敞开心扉而叹息。

“为什么她会那么讨厌你？鸳野你没有任何不对啊？从你的话听来，你明明特别重视她。”川喜田感到很奇怪。

“她对鸳野有特殊情结。增冈不是完全不会做家务嘛，但鸳野很擅长这些，恐怕让她心存芥蒂。”阿叠说道。

“这种事根本没必要放在心上啊。”鸳野耸肩：“我什么都没帮上，当初应该还能为她多做些事的。”

“哎，这也没办法，是她自己选的。”阿叠难得安慰别人，鸳野却仍是一副放不下的神色。

“曾经有一回，真赤吃了药，精疲力尽。记不得是因为她大闹，还是大声哭喊，还是生了病，我由于担心，到身边陪她。真赤看着我说：‘鸳野姐姐长得真漂亮呀’。她自己那么漂亮，竟然看着我说这样的话。我怎么也忘不了这件事。”

言罢，鸳野沉默了。

“哎，怎么说呢，发生了太多。”阿叠苦笑，然后又弹起吉他。

“总之，好在一路走来大家都还活着。不光是增冈，其他人也受了不少罪。”说着，我也耸肩。

“说得没错，增冈刚来的时候可真是要命。”

我们都笑了起来，鸳野却紧皱眉头，抗议般地说道：

“不奇怪吗？为什么水屋口哥和叠泽哥都刚才一直用‘增冈’这个网名叫真赤？之前明明不用这个称呼呀？”

夜越来越深，在天快亮的时候，大家入睡了。

床上用品没有多余，我们便挤在地板上睡，将外衣盖在身上。气温寒如隆冬，可暖气设备只有一台小小的燃油暖风机，即使调到最大风力也不足以暖热整间屋子，冷极了。

我在坚硬的地毯上辗转反侧，终于产生些许困意，却又立马醒来。天已经亮了，白色的阳光从窗户射入房间。其他人正睡得香甜，发出阵阵鼻息。真亏他们能在这种环境下睡着。尽管失眠短暂消退，我还是无法熟睡。

既然是临近天亮才入睡的，估计大家要到下午才会醒来吧。独自不出声地等到那时候可太难了。我试图睡回笼觉，却始终难以入眠。正想要出门买烟时，我发现钱包不见了。

黑色大衣的口袋中没有，已经穿旧的牛仔裤兜里也没有，在插座上充电的手机旁依然找不到。最后一次见它是在深夜去附近便利店买东西的时候。万一是在路上丢的，我现在必须立即出门寻找，但在此之前需要核实钱包确实不在房间里。

我尽量控制翻找的动响，以免吵醒其他人，可怎么找也找不到。真的掉在外面了吗？这片街区深夜也会有人经过，我难道不小心把它掉在路上了吗？

一想到这种可能，我背后冷汗直流。里面的东西可以放弃，可钱包本身无法挽回。

在我慌乱地寻找之时，发出的动静把鸳野吵醒了。她眯着睡眼，向我看来。

“鸳野，我的钱包不见了，真赤给我的钱包，不知道去哪了。”

鸳野不可能知道它的下落，但这白费口舌的话，我却忍不住不说。我明白自己张皇失措，可对此束手无策。

“你知道它在哪吗？去便利店的时候好像还在……”

明知问她没有意义，我还是觉得她应该能理解我惊慌的心情。

然而鸳野似乎只是睡迷糊了，呆呆地盯着我，接着一言不发地合上了眼睛。

在那之后，我在厕所的地上找到了完好无损的钱包。长舒一口气后，我回到房间告诉鸳野钱包已经找到，可她已完全睡着，没有任何反应。

“哎呀，好久不见，过得好吗？脸色不怎么样啊，可得好好吃饭，哈哈。我都到了这个年纪，每天食欲还很旺盛，吃什么都能吃到饱。”

时隔良久，柾木社长依然那么开朗活泼，对我没有任何芥蒂，仿佛已经忘记我过去的忘恩负义，令我不知如何是好。

“听说你还想来我这里工作，已经不要紧了？身体好了吗？”

“是的。”我点头：“当初真的非常抱歉。”

我们位于涩谷的一家中式餐厅，奇妙的是，这里正是我上次与柾木社长见面的地方。当时我好像是为了谈辞职的事而来的。

在那之后过了一年有余，如今我为了完全相反的目的，和他对坐在这里。我主动提出希望他能再次雇我。

无论应聘多少份工作都得不到录用，这不单是麻烦，更是屈辱。

每当面试落选，我都仿佛受到了“社会不需要你”、“你一文不值”的评价，感到非常气愤。私生活且不谈，对于工作我还是抱有一定尊严的。

只要我有心，肯定也能相对轻松地拿到平均水准的收入——不先证明这一点，树立起自尊，我还怎么干得下去，还如何积极地活下去。要是连这仅存的一点自尊都失去了，那我就只能躲进阴暗的地穴中度过余生。

恬不知耻地重返曾经辞退的地方实在丢人，但只要看开就好。我已经没有需要维护的脸面了，不会再像以前一样，把“收入太高，我怎么也受不了”这种荒唐理由挂在嘴上，这件事已经彻底过去了。

一旦厚起脸皮，给柾木社长打一通久违的电话也变得轻松无比。

“我很吃惊你会突然联系，一般逃跑之后是不会回来的。有什么心态上改变吗？”他一边品着上来的菜，一边说道。我迫不及待地开口：

“我过世的祖父是位商人。他原本在一个乡下大家族，是同辈中的小弟，没怎么上过学，来到东京给商家当学徒。生意做得还算成功，最终在东京市内有了几片土地，还有住着医生的公寓楼呢。前不久走亲访友拜年的时候，我去了他那里。仰头看着那巨大的公寓，我动了心，想要变得像他一样。机会难得，我想尝试挑战。尽管从继承权上来说，我一文钱也分不到，但我身上流着仅凭一代人就建立起这番伟业的血，不能一直游手好闲下去。我想要丢掉无谓的拘泥，好好工作。”

虽然并非全是谎言，但也说不上是事实。总之，在我一面极力避免透露最重要的部分——想要轻松赚钱——一面滔滔不绝地诉说这似是而非、谁也体会不到的心情时，柾木社长点头：

“是吗，那太好了。年轻人就该有梦想！”他依然摆着平时那副笑容，不知是信以为真了，还是当作了耳旁风，让人捉摸不透：

“既然如此，就让我来助你一臂之力吧。”

“非常感谢。”

“然后呢，昨天接到你的来电之后，我立马开始考虑该让你去哪工作。”

果然，柾木社长还是和以前一样好说话。

“我想让你重新回之前的地方。”

“又、又要去修打印机和电脑之类的东西吗？”

“没错。如果你实在不愿意的话，我也可以给你介绍其他工作，不过难得学会了一身技术，还是能活用为好。至于工作条件……你之前说要辞职的时候，我不是答应给你涨薪吗？就以涨后的工资为准如何？”

他的提议出乎意料，可我岂有拒绝的道理。当时我几乎没有任何迟疑：

“明白了，那就拜托您了。”

很快，第二天我就前往了公司。

上班高峰过后，电车中十分冷清。我放松地坐在座位上，透窗的阳光暖热了后脑和肩头。

轨道架在高楼大厦之间，电车在其上穿行。按照在家查的时间，距到站还有一小时十分钟。过去从花园公馆去上班只需不到三十分钟，现在真是远了不少。

一想到今后每天这段时间都要花在通勤上，我的心情就很郁闷。不过，考虑到这份工作和其他平均水平工作的收入差距，已经足够合算了。我用这样的想法压抑自己的不满。

真不想像这样操控自己啊，总觉得这是在用金钱驯服人类本身的自由天性，是肮脏的做法。不过，恐怕这正是我所欠缺的吧。到头来，自由是无法带来什么的。

随后，我到达了目的站。我乘坐的那辆电车沿着线路继续奔行，终将经过我怀念的街道，那条花园公馆所在的、大家曾住在一起的街道。

时隔约莫两年，同我当初每日通勤时相比，站厅内的样子别无二致。搭乘完扶梯，从小商铺前走过，彼时的感情鲜明地复苏。那时我和真赤住在拥挤的房间里，从早到晚大脑都受着药物影响，每天都在生活与劳动的疲乏中度过。来到这检票口时，心中总是带着混沌而炽热的情感。相比之下，我现在心境非常宁静、平和，尽管一切都没有丝毫改善。

伴着恍若隔世的感觉，我穿过检票口，踏上台阶，站在令人怀念的楼前。而后，我像曾经那样，对着大楼的玻璃整理发型和领带。这时，一阵感觉突如其来地涌现——马上就要重回那间办公室了——使我紧张起来。

我曾单方面丢下辞职信后走人，要是觉得能被轻易接纳，那想得也太美了。当时的同事肯定认为我没有责任心，心里十分不快。情况很棘手，但也没办法，全都是我咎由自取。必须先把这些负面影响消除，之后才能重新上路。能为过去负责反而不是件坏事。我一直耿耿于怀。

只要这样暂时加把劲，肯定可以取回之前的信赖，然后就又能像过去一样，拿到远超其他人月薪的报酬。在此之前，我必须将意志化为钢铁，覆盖在精神表面。

“好！”我小声给自己鼓劲，然后步入大堂。

搭乘电梯到达公司所在的楼层，员工们都已外出，楼宇静悄悄的。窥了一眼左侧内部的吸烟处，没有人在，只有一台看上去性能强劲的空气清新机在安静地运转。我还在的时候是没有它的，大概是新买的吧。

门上挂着令人怀念的公司铭牌，我打开门，进入事务所。布局同过去没有丝毫改变：长桌摆在那里，右手边则有两位员工正同一台A4黑白激光打印机鏖战。

他们脱了大衣，剩下衬衫，袖子卷到了肘部，在进一步拆分已卸下外壳的打印机，但似乎是对操作步骤不放心，正在四处检查。他们两人看上去都比我年长许多，不过会在激光打印机的这种程度陷入苦战，说明入职时间应该不长。

对面是主管的坐席，这个过去属于间户场主任的座位如今正被别人坐着。那个人应该是上野分部来的新井先生。实习期间我到上野分部出勤过几次，记得当时承蒙了他的照顾。进入公司前，他曾以职业乐手为目标，热情投身于乐队活动，有着奇妙的经历，一谈起音乐就会兴奋。

他电话正打到一半，在给对方做技术指示，另一端大概是给顾客上门维修的技师吧。察觉我来到了面前，他竖起一只手，摆出让我稍等片刻的手势。

“哎呀，好久不见，正等你呢。”电话结束后，新井先生爽朗地说道。

“好久不见，现在是您负责吗？”

“是呀，间户场主任去新成立的事务所了，前不久刚把这里交给我，忙得要命。听说你要回来，我高兴坏了。以后就靠你啦。”新井先生戳我的手肘，笑了一笑，然后又举起话筒：

“你来了，我给部长说一声。”

“要、要告诉部长吗？”

“是啊。哎，别紧张，没事的。”

最早我和柾木社长一同参加面试时的负责人，就是刚才提到的部长。他高挑的身材、威严的气质、以及不时显露出的暴脾气，使他成为全事务所最令人畏惧的角色。

尽管他不会无故发火，但如果事出有因，他会暴跳如雷，把犯错的员工斥责得泪眼汪汪，可怕极了。我们背地里怀疑他原来是不是混黑道的，对此还偷偷一本正经地议论过。

我曾以近乎失踪的方式辞职，恐怕也要为这件事被咆哮。不，以部长的性子，视情况甚至有可能动拳。哎，不过吃上一两拳倒没有大碍。别看现在这样，我以前可是运动员，有挨教练打的经验。挨揍这种事，其实没什么大不了。

我一边给自己鼓劲一边等待。很快，部长进入了房间。他是一个眼神锐利的人，面色严肃地看向我。

“哟，是水屋口吗。”

“是的，还请您再次多多关照，过去的事十分抱歉。”我低下头。

“哦，请多指教。”部长的态度出乎意料得温柔。他伸出右手，我便握住。

“我记得你是和三田同一批进来的吧。”

“是的。”

“他已经长进了不少，现在是这里的王牌，开着车麻利地完成任务。以前你更优秀，现在可要向他看齐。”

“我明白。”

没有受到预想中的斥责，我内心松了一口气。部长微微一笑：

“你呀，肯定以为会被痛打一顿吧？这回饶了你，但没有第二次。”

他轻轻拍了我的肩，然后离开了房间。

随后，新井先生把我介绍给刚才的新员工。新来的两人比我年纪大，一位个子高，一位有点胖。他们知道我的名字，令我很惊讶。他们说前辈讲过，我在被派去当活祭的地方偶然修好了大型喷墨打印机。

“我还一直好奇是个什么样的人物呢。”胖的那位新员工笑道，一边抚摸着自己的脸，闪着黄铜色的手表戴在手上。

介绍完毕，当天的事就结束了，但新井先生叫我和三田见一面，我便等他到来。

等待的期间，我向管理仓库的大爷打了时隔两年的招呼，又把自己的新手机号给了摩托快递员，接着翻看事务所的储物架，收集看似没人用的工具，为明后做准备。这时，我发现了一个眼熟的包。

那是我两年前放在这里的工具包。当时它还是崭新的，如今却已被用得破旧，到处都是磨损的伤痕。

“啊，这不是水屋口哥嘛。”

正当我抱着它感到怀念时，三田回来了。许久不见，他依然是那个使人眼前一亮的美男子。见到我，他开心地微笑起来：

“我很快就能把文件整理完，可以先抽两根烟等等我吗？”

我点头作为回答，然后照他说的在吸烟处等待。

口袋里，Peace长烟的软烟盒已经被压得满是褶皱。为了防止把烟弄断，我小心翼翼地用指尖取出最后一根，把它抻直，叼在嘴里，接着点燃。烟里含着Peace特有的甜香，吸入肺中，成分在脑内生效的感觉传来。最近我在节省烟草钱，偶尔的一根会效果过度。

抽烟的同时，我回想起初中时展示的烟民肺部解剖照。橙色的肺里纹理粗糙，沾满了污黑的焦油，宛若浸泡了淤泥的篮球一般。我的肺也在渐渐变成那样吗？

空气清新机是桌型的，兼备烟灰缸。我把烟头放在了烟灰缸部分，升起的烟气被迅速吸入。我心不在焉地望着这幅景象，这时，三田迈着大步赶来了。

“好久不见，你还和以前一样瘦，身体好吗？”

“嗯，还可以，三田你呢？”

“我身体结实着呢。啊，能借个火吗？”

我点头，他便拿起我放在清新机上的廉价打火机，点燃了柔和七星159。

“我听说你变成这里的王牌了，真厉害啊。”

“哪里，没什么大不了的。”他笑着掩饰自己的害羞：“你可能已经听说了，公司成立了一个新的分部，老手都调到那边去了，会开车的只剩下我，自然重任就压在身上……不过，开车真的很有趣。拜此所赐，我还胖了一点呢。”说着，他拍了拍在我看来毫无变化的肚子。

“新井先生说现在人手短缺。”

“是啊。新人也总是呆不长，但有水屋口哥回来就能安心了。”

“我做不了什么，只会修激光打印机。”

“以你的能力马上就能学会，没有多难，到时候很快就能赶超我。”

“你太抬举我了。”我耸了耸肩：“话说，真的有那么多人走了吗？如月前辈他们离开了？”

“对，儿玉前辈也被调走了。”

“元山呢？”

“你走后不久他也辞职了。”

“荒垣呢？”

“还在，矢尾板也在。”

“是吗，那确实变了不少。”

“哎，会有机会见面的。对了，真赤还好吗？”

“不清楚，和她没有联系了。”

“什么！这样啊，真遗憾。”三田皱起眉头：“那你现在没有女朋友？”

“嗯，你有吗？”

“嗯，算是……不过，既然如此，水屋口哥，你周末有空吗？有空的话就来踢室内足球吧。好久之前大家就一起在踢了，很有趣的。”

“哦，当时的提议最后实现了啊。”说完，我将抽完的烟在烟灰缸上掐灭，丢进其中。

“你什么时候开始工作？”

“从后天开始。”

“哦。因为你有一段空白期，最开始应该是参加双人维修。这样一来，肯定是和开车的我组队。到时候我们又能像以前一样两人一起工作了呀。是不是很怀念？”

“是啊。”

“我姑且粗略地学会了点阵、喷墨打印机之类的知识，能给你教。我居然给水屋口哥教机器知识，感觉好奇怪……但是，你能回来真是太好了。”

之后我拒绝了他的晚餐邀请，搭上了回家的电车。

车厢同来时一样空荡，每当摇晃，所有吊环都会跳起一丝不乱的排舞。我有意无意看着它们。

我心中一片嘈杂，毫无消退的迹象。

为什么大家都那么温柔呢？尽管已经隔了一段时间，可他们是清楚我过去是怎么辞职的。非但如此，我不在的期间新加入的人甚至也听说了传言。就连那个严厉的部长都没有表现出真正发火的意思。

我本以为肯定要让我负一定责任，都已准备好接受他们的敌意。说到底，我这样的人，纯粹是冲着高额薪水才回来的，决不应受到这样的接纳。

我对他们完全没有信赖。长久以来，无论走到社会中的什么地方，我都被强加了“不被需要”的烙印，彻头彻尾被当作废物对待，没有任何地方愿意接受我。我已被迫习惯，被迫视作理所当然。

说真的，他们为什么会以如此和气的态度迎接这样的我呢？我无法在这里工作，没有资格。

回想起方才大家对我的亲切与期待，泪水不住地流了下来。

在那之后我工作了一个月，所有人依然对我很温柔，工作快活又开心。我心如刀绞，没能融入其中。我不应留在那里，没有这份资格。我就适合呆在反人类的地方。

我去找荒井先生商谈，受到了他的挽留，但我已不愿回应。我执意辞退，然后立即给柾木社长打去电话。

我告诉他自己实在无法在这里工作，他很诧异，询问我原因，但我无法开口。接着，他又提议说如果我不喜欢这里，他可以为准备一份别的工作。我同样拒绝了。

柾木社长想要问出理由，然而我说不出口。要是我如实道出自己的感受，他究竟能不能理解呢？说到底，真的能有人理解这样的感情吗？连我自己都做不到。

而后，我又开始求职，但已迷失自己寻找的目标。每天都困倦无比，几乎无法思考，没有面试的日子我就一味地在被子里消磨时间。

柾木社长打来了好几通电话，我没有接。

过了一段时间，某天母亲给了我一封信，是柾木社长写的。

公务用的白色信封上由他亲笔写下了我的名字。没有邮票，更没有邮戳，看来是他上门造访了我的住处。我似乎没有注意到对讲机的铃声。访问以落空告终，而这封信应该是他现场写的留言吧。

信中恳切地写着为我担忧的话语，以及工作与人生的一些道理，然而我太过痛苦，没能将这些文字读下去。

我把没有读完的信照原样装回信封，然后收入桌子最下方的抽屉。

第二天，我去见了母亲，拜托她：可以的话，请把我送进精神病院。

四

根据医生新做出的诊断，我得了抑郁症。不知道实际是不是这种病。我没有像过去那样刻意在诊察时撒谎，但也不信任心理医生。

抑郁症患者似乎有一栋专属的病房楼。那里和“精神科病房”五个字历来给人的印象不同，是为疲于工作或应酬的工薪阶层治愈身心的舒适、时髦场所。

原本我应该住进那里，但或许是经济萧条的原因，医生说所有的床位都满了，没有空余，建议等待腾出空位，可如果无论如何也想立即住院，那就得去更为古典、更为正宗的精神科病房楼——不光有抑郁症患者，还住着各种各样的病人。

对我来说，但凡是被隔离的地方，去哪都无所谓，何况光是想象一下生活在死气沉沉的抑郁症患者的包围中，我都觉得厌烦，而且既然要住精神病院，那就该体验其精髓。所以，古典的病房楼反而更使我开心。

“没关系。”我立刻答道。

“真的不要紧吗？那里可都是有些怪的人啊。”医生叮嘱道。这话真不礼貌，我心中想道，一边回答：

“没问题的。”

我情不自禁苦笑，医生露出了奇怪的表情。

就这样，我得以正式入院。网友之中有几个人住过精神病院，所以我并不像常人一样对这类场所抱有特殊印象。

话虽如此，由于没有实际亲眼见过，入院之前，我确实多多少少将其想象为《飞越疯人院》160、《移魂女郎》161等影视作品中描绘的世界。实际上既有相似的部分，又有截然不同的地方。

我住入的建筑远比想象中的医院粗糙。

墙上贴着似乎是胶合板的薄板，墙纸也未经加工，暴露在外。地板掉了漆，粗涩不平。

除却嵌在窗上生了锈的铁栅栏，这病房空荡的景象和我小学的装配式162校舍别无二致，隐隐唤起了我的乡愁。唉，那时候真痛苦。虽然现在处于这样的境地，但仅凭自己明白堕入这步田地的缘由，就已经比一切都不讲道理、无处可逃的少年时期要好得多。

床由掉了漆的铁管组成，很简朴，室内共有六张。目前已有五个人在此生活，我来之后就占满了。

正如医生事先警告的那样，住在里面的人有些怪异。

首先是睡在我隔壁的S，他好像得了无法与人交流的病。本以为他一句话也不说，可他却会一边嘟嘟囔囔自言自语，一边在屋内一圈圈地走来走去。要是绕圈过度，他还会难受地倒下。

S对面是D的床位。D几乎可以说是一名少年。虽然他平时和人交谈时显得聪明伶俐，和健康人没有区别，可一旦触发某种条件，他就会开始控诉自己遭受了毒打、盗窃等子虚乌有的伤害，连带着加害人的姓名，给周围人添麻烦。

睡在我对面O从早到晚都摇着身子，反复地歌唱动画《龙珠》163的片头曲。大部分时候即使和他打招呼，也没有回应。

床位离房间入口最近的T是位腰杆笔直的老人，看上去是这间病房里最正常的一个，但有时会突然放声大哭，好像是由于被家人抛弃才来到这里生活。他在外面做了什么啊？

不必多说，怪异的不仅仅是这间病房的人，整栋楼里的全部患者都得了病。走在走廊中，总能见到一些人受病症驱使的行为。当然，没有人对此大惊小怪。

在外面被视作异常的举止，在这里都得到了宽容。即使自言自语一些让人无法理解的话、做出莫名其妙的行为，只要不伤害到自己或他人，就没有人会追究。一切都自然而然地存在，这实属罕见。

此外，这里不存在任何目的。除了固定时间要到护士站前排队领药之外，没有其他称得上是治疗的行为。所有人一天到晚都过着随意的生活，比如在吸烟处和其他患者下将棋、在大堂呆呆地看电视、等等。时间平静地流逝。要说这就是治疗的话，也许没错，可这里并没有相应的积极气氛。

我听说有很多精神疾病无法彻底治愈。一旦患上这类疾病，可能要在此处生活数十年。这样的生活长期持续下去，回归社会大概没有指望了。实际上，这里的患者尽是老人，恐怕他们今生都等不到出去的那天，将在这里走向终结。或许，这里是弃老山164一般的地方。

这就是绝望吧。患者之中也有人抱有同样的感觉。不说全部，少数人似乎还怀着有朝一日回归社会、和家人朋友一起生活的愿望。对他们而言，这里无异于牢笼。不过，一部分患者已经连这样的念想都没有了，而我也丝毫不抱有同样的感情。毕竟我是在外面经历了惨痛的失败后主动前来的，会期盼出去才奇怪。

而且，说实在的，入院没多久我便意识到，对我来说，这里舒适极了。

天呐，这里太棒了。虽然外出受到限制、没有谈话对象、网络自然也受到隔离、不能自由听音乐，然而这些都不痛苦。粗糙的墙壁和生锈的铁栅栏帮我赶走了外部世界的一切麻烦。在这里，我无需做一个正常人，安安静静地闭着嘴就是在尽自己的责任；不会被喜欢，也不会被讨厌；不需要一遍遍地重复说明来让不懂的人理解。我感到了纯粹的安心，这在外面的世界是绝不可能得到的。

来了之后，我发觉对事物怀有的希望、抱持的期待，对于自身而言无非都是压力，发觉医院之外没有任何我想要的。之所以感到有所欲求，仅仅是义务感在作祟，认为自己必须如此。

真是自在的生活！如果要说明我的一天，情况大致如下：

首先是起床。起床后早饭很快就会送来，我便在床上用餐，之后立即睡回笼觉，不过大多会被护士叫醒。上午不能外出，我就在病房发呆度过。

很快到了中午，午饭开始了。每日三餐的份量和味道都不够，明明一点也不好吃，但不知是不是生活过于单调的缘故，开饭是我每天的一大期待，使我格外高兴。我有了加餐的习惯，体重渐渐增长。差不多自高中以来，我的体型基本没有变过，所以很惊讶。

由于只能在白天特定时间外出，吃完午饭，我大多会去车站前的小书店买上几本书。要是酒虫作怪，我会趁外出的时候买一包纸盒装的酒，偷偷地喝。

回来后一直到晚饭前，我会读买来的书。或许是因为比平时更容易专注，我在医院里读了相当多的书：司马辽太郎的《宛如飞翔》165、梅图一雄的《我是真悟》166、托马斯·曼的《魔山》167、内田百闲的《阿房列车》168。电视旁放着十几年的文艺春秋芥川奖揭晓期169，手边无书可读时，我便跳过获奖作品，只看石原慎太郎170和宫本辉171的评语。

享用完期待已久的晚饭，熄灯之前我会继续读书、吃白天买的零食、等等。

药会在餐后固定时间发配，需要端着盛好水的马克杯在护士站排队，当着护士的面喝下，但我只装个样子，然后立马拿到厕所倒掉。医院开的药似乎要比在外面服用的强，吃完觉得脑袋迟钝，像变傻了一样。我很不喜欢这种感觉。

我在精神病院的生活大致如此。

每周仅有两次洗澡的机会，而浴缸里总是飘着患者们的体垢，泛着一股恶臭，所以我只愿意冲澡。此外，护士对我讲话的语气像是对小婴儿说话一样。我只看不惯这两点，其他基本上很满意。我过去体验过如此健康的生活吗？

呆得越久，我就越发好奇当初为什么没有早点来。我这个人啊，就该作为一个精神病在精神病院过一辈子。要是能早点察觉，我就不用走无聊的弯路，无需伤害他人和自己了。

回想起在外面做过的事，我羞愧难当。试图去适应，却以失败告终。我在自己的心中什么也没能寻获；没能培养出体会幸福的感性；没能爱他人、为他人所爱。我所做的一切都没有必要。只要呆在这里，我就不会再出那样的丑，也不会对任何东西产生渴望。

我本打算就这样一直住到条件不允许为止，然而意外的转机到来了：我入院前面试的公司发来了再迟不过的合格通知。

烦恼了一整夜，最终我决定离开医院，去那家公司上班。

精神病院确实是个好地方，可我随时都能再回来。然而工作就不一样了，时间过得越久，履历中的空白期就越长，就职恐怕也越难。既然如此，我不就应该暂且去上班，赚取自己的入院费吗？这里的生活虽然开心，费用却是母亲出的，我很心痛。

于是，收到联系的第二天，我提出了出院申请。

本来就是我自己请求入院，一说要离开，当天就可以出院了。这方面的情况我和其他患者不同，令我有些过意不去。

之后，我成功复归了社会。这次的回归出乎意料，我完全没想到。

我的新工作单位是一家位于新宿的小型编辑公司，工资低得无法想象。制作的是色情杂志，为了弥补人手不足，什么都使唤我做。环境虽然如此严酷，我却没有立刻辞职。

是因为不知不觉中，我很大程度地恢复了吗？现在我已不再依赖精神药物，也不会莫名发烧。

尽管如此，一开始我还是对医院的生活无比怀念，可渐渐也就忘了。编辑公司的工作本身并不有趣，忙得不可开交，没有时间思考多余的事。

过了一年左右，公司破产了，但这份经历似乎已使我找回了劳动的习惯。很快我又开始寻找下一份工作，并且求职期间也在打工填补空闲：盖楼或施工现场的工作、交通流量调查、发放餐巾纸广告。我不愿腾出无所事事的时间，像过去一样变得堕落，便一味埋头于工作中。居然采取如此积极的行动，我对自己感到很不可思议。

而后，以往绝不会表扬我的母亲也开始时常夸赞我。虽说这些话语是我少年时想得到的，但感觉不坏。

母亲清晨早起，为我准备带走的盒饭。我已经多久没有吃到母亲做的盒饭了呢？

在施工现场，我大口大口地吃着已经放凉、有些变硬的米饭，泪水扑簌扑簌地流了下来。

我不再逛文本网站了。过去疯狂更新网站的热情有如假象一般，周围的人也要么关停，要么放置不管。

过去自称为“脱线类网络偶像”的卧村亚弦已同样不再打理网站。每次我在聊天软件上搭话时，她都在编织东西。为什么要表现得这么女性化，这么端庄贤惠？我坦率地提出自己的疑惑。她回答说自己原本就是安静的人，现在只是变回原样而已，语气十分冷淡。

她是和我交情最久的人之一，我成立网站之初便认识了。一直想和她见上一面，然而最终还是没有这份机会。而后她渐渐不再上线，不知不觉中消失了。

她的生活已不需要网络和其中的人际关系了吧。对我来说也是一样。

刚开始工作时，我还多少更新一下“电气马戏团”，而后来不知何时中断，不久连它的存在都忘却了。很长时间后，我将服务器中的数据全部删除，那时心中也没有任何感慨，只对自己的无动于衷感到一丝落寞。曾经的日记瘾像是虚假的一般，我没有任何感情起伏。

眼下文本网站似乎整体在衰退。博客172出现，包含艺人在内的各路人士都开始使用，网络本身在逐渐变性，写手和读者的群体也随之变了。

当然，虽说已不再写日记、更新网站，我并非脱离了网络。

网络本身要比过去方便得多，已经渗入生活的各个角落，想要和它切断关系是不可能的。

尽管如此，即使我启动了电脑，也不再同网上众多的熟人往来。

一旦和圈子疏远，手机上也不再收到活动或是酒会的邀请。我并不是刻意拉开距离，只不过经历了这样的过程，不知何时，我和“网上的人们”关系变淡了。

就这样，一切都渐渐沉淀为回忆。有一天，为了更换用旧的手机，我整理起电话簿。这时，真赤的名字忽然映入了眼帘。

尽管已过去许久，看到这几个字，我胸口仍然会痛。我对她做出了无可挽回的事——时到今日，这股歉疚感还未消失。

再怎么说，那时的她处于敏感、易于受影响的年龄，而我身为一个成年人，做得实在太差劲了。就算我也和她一样处在寻找之中，但这并不能当作借口。有时一想起自己可能给她的人生留下了阴影，我就感到胸口苦闷。

真赤是个在网络圈子中比较显眼的人，所以虽然没有直接联系，我还是有机会听到关于她的传言。她成功考上了大学——这是为数不多的好消息，其余的都使人高兴不起来：每次线下会她都会跟不同的男人回家；做了美容整形手术；隆胸；当大学教授的情人；成为了社会运动家，和同伴一起给政府抛出蛮不讲理的难题。

流言是从网上的那伙人嘴里说出来的，不值得相信，但我和网络圈子的联系已经淡化，没有验证真伪的途径，然而每次听到我都会忧郁。

她现在过得还好吗？想着这些，我忽然按下了拨号键。

我没想到能够拨通。我曾经被她拉入了拒接名单，可能她已经把我的名字删除，拒接的设置也消失了吧。呼叫的声音响起。

明明是自己拨的，我却有些紧张。

“……喂？”我很熟悉这明显带着警戒的声音，它无疑属于真赤。

已经过去两年了吧？我向她打招呼，但她没有认出是谁。我报上了名字，终于，她惊讶地叫出声来。

接着，我们聊了半个小时的家常。

她现在就读于某所著名大学，正在和一位外国朋友合租。她的学生生活似乎过得还蛮开心，声音很明快。我说自己正在公司上班，真赤笑着调侃：没想到我居然能踏实干活。

大致汇报完近况，她最后说道：

“以后要经常联系啊。”

我含混地回答，随后通话结束了。

我不知道该拿她的态度如何是好。

她的语气轻快到了让人泄气的地步，看来她已经忘记了当初的种种。此外，自始至终她都用着“水哥”这一亲昵过头的称呼。

以前，她无论何时都叫我“水屋口哥哥”，不会用如此随意的昵称。估计是进入大学后，随着她成长、与形形色色的人邂逅，她对于外人的感受也发生改变了吧。我有种和普通女大学生谈话的感觉。当初她三言两语就会给人留下特别的印象，如今已完全不会了。

不管怎样，她似乎没有想象之中那样讨厌我。第二天我给她发了短信，询问能不能给她打电话。

然而，刚发出去我就立马后悔了。她已不再是我所熟知的那个特别的真赤，也过上了新的生活。然而我之所以还想联系她，仅仅是为了可鄙的目的，只要是女人任谁都无所谓。这样的自己令人反胃。

于是，在收到回复前，我又发了一条显得像是在生气的短信，声称上一条作废。她肯定觉得莫名其妙吧，或者认为我依然患有精神疾病。怎样都无所谓，必须在此做一个了结。

她没有发来回复。

这就是我和真赤最后的接触。至于此后她过得怎样，我再也没听到过传言。
