#+SETUPFILE: ../../setup.org
#+FILETAGS: blog

#+TITLE: 如何正确地使用他人的作品
#+DATE: [2023-02-14 Tue 17:02]

如你所见，我写的文章一般都会带上一张封面，我究竟通过什么方法在自己不会作画的情况下还能贴一张图呢？那自然是直接拿别人的图了（笑）。在这样写了几十篇文章之后我逐渐意识到了还有版权这一回事，似乎我已经在无意之间侵犯了他人的权利。虽说我写的东西就是一点小打小闹，但是这方面还是注意一点比较好。

本文的主要目的是在了解一些简单的的作品相关知识的同时学习如何正确利用他人的作品和成果。我并不指望这些知识在逐渐深化网络化的当下和未来还能有什么作用，再过一段时间这样的做法也许就是过时而滑稽的了。但是了解一下也没什么坏处就是了。

于我而言，了解这方面的知识是为我写点小文章这个目的而服务的，所以包含的内容不可能很大很全（当然我也做不到），本文中可能会涉及到文字，图片，音视频以及代码相关的问题。需要声明的是，文中没有出现引用的内容大部分都只是我认为有道理的观点或陈述，如果要严肃地了解这方面的知识，请阅读权威资料或咨询权威人士。

{{{toc}}}

* 什么是作品

在思考“什么是作品”这个问题之前，我对作品的认识就是出版的书籍或音乐影视绘画等艺术品。下面我试图找到一个可以“包括一切”的作品定义，由于我自身的法盲属性和缺乏作品判定的相关实践，请注意不要被下面可能出现的常识性错误或偏见误导。如有错误欢迎指出。

我对作品的认识是非常模糊的，不过肯定并不是所有的人类活动产物都能看作作品。就拿日常生活中的用品来说，我们 *可能* 不会认为 *实用性太强* 的东西是作品，而是将它们视为物品，比如纸张铅笔、电脑电视、锅碗瓢盆、硬盘 U 盘、手表手机、桌椅板凳、公交地铁、等等（请原谅我贫瘠的生活体验）。但是对 *另一些东西* 我们又非常自然地将它们视为作品，比如绘画、雕塑、摄影作品，文学作品，音乐作品，舞蹈作品，影视作品，手工制品，建筑作品和设计作品。究竟是哪些因素决定了我们将某个东西视为作品而不是物品呢？

我不太可能去翻法律文献，也不太可能就这个无聊问题去折腾律师咨询，这里就直接给出我对作品的认识： *具有独特价值的人造物* 。作品可以简单到纸上的随手涂鸦，也可以是《战争与和平》一样的长篇累牍，只要有人能够发现区别于一般物品的属性，那么物品也就成了作品。这种独特性的来源可以是作品中的创造性成果，可以是物品带来的审美体验，可以是物品具有的艺术价值，可以是物品具有的文化背景或象征意义... 凡是能被看作作品的东西一定要有这样一种独特感，至少我是这样认为的。这种独特感的来源可以是多样的，也可以是随时间而变化的。

参考[[https://zh.wikipedia.org/zh-hans/%E4%BD%9C%E5%93%81][维基百科]]上的说明，作品指“具有创作性，并且可以通过某种形式复制的成品，著作权法保障了这些创造性活动的表现形式，作品的创作者就是作者”。现代汉语词典第七版中对作品的定义是：文学艺术方面的成品。顺着词语定义中出现的词语，我多查了一些词的定义，以下内容均来自现代汉语词典第七版：

#+BEGIN_QUOTE
- 【作品】：指文化艺术方面的成品，如绘画作品，诗词作品。
- 【成品】：加工完毕，可以向外供应的产品。
- 【著作】：用文字表达意见、知识、思想、感情等。
- 【著作权】：著作者按照法律规定对自己的文字或口头作品等所享有的专有权力。属知识产权范畴。其中的发表权、署名权、修改权、保护作品不能转让；复制、发行、出租、表演、广播、展览、网络传播、摄制等权利可以转让和继承，也叫版权。
- 【著作权法】：调整著作人因创作作品而享有的某些财产权和人身权的法律规范。我国也叫版权法。
- 【版权】：①著作权。②出版单位根据出版合同对特定作品所享有的出版权和销售权。
- 【知识产权】：在科学技术、文化艺术等领域中，发明者、创作者对自己的创造性劳动成果依法享有的专有权。包括工业产权和著作权。
- 【知识】：人们在社会实践中所获得的认识和经验的总和。
#+END_QUOTE

字典中的定义强调了作品要是文学方面的成品，不过根据我的理解作品是人造物就行，只要它具有某种意义上的独特性。对我来说法律和官司可能太遥远了点，所以我也不一定要拘泥于字典上的定义。（随着人工智能的发展，也许之后我对作品的认识会被修正为 *具有独特性的物品* ）。

* 为什么要有知识产权

如何使用别人的东西这个问题迫使我开始了对道德、法律还有权利的思考，然后我马上悲哀地发现我对这些一窍不通。得亏大学时我上过一门叫做《知识产权导论》的课，至少是看过一些名词，所以我选择“知识产权”而不是“著作权”来作为这一节的标题，知识产权的范围更大一些。

所谓“存在即合理”，一个东西既然存在那一定有它的合理性，在这一节中我尝试对为什么会有知识产权这回事找到一个令我满意的解答。

** 为什么会有道德和法律

相对于法律来说，道德对我来说更加具体一点，比如“道德高地”，“道德武器”，之类的，所以我们先从“为什么要有道德”这个问题开始。

道德对我们每个人来说应该都不是陌生的，比如公交车让座和老幼病残孕专座，“向前一小步，文明一大步”，随手关灯，汽车礼让行人，路不拾遗，待人礼貌，等等。道德是提倡性的而不是强制性的规则，它提倡对他人和群体有利的行为，劝诫对他人和群体不利的行为。维基百科的“道德”词条的第一段是这样说的：

#+BEGIN_QUOTE
道德（英语：moral；源自拉丁语：moralitas，即"举止，品质，适当的行为"）是依据一定社会或阶级（生活形态）的价值观、社会舆论、传统习俗和人的内心信念的力量（生产能力）来调整对他人和自己之间的行为进行善恶、荣辱、正当或不正当等的相互关系（生产关系）的评价和断定的行为规范标准。有着通过确立一定的善恶标准和行为准则，来约束人们的相互关系和个人行为，调节社会关系，并与法一起对社会生活的正常秩序起保障作用。贯串于社会生活的各个方面，如社会公德、婚姻家庭道德、职业道德等。

[[https://zh.wikipedia.org/zh-cn/%E9%81%93%E5%BE%B7][道德 - 维基百科，自由的百科全书]]
#+END_QUOTE

在这个定义中，道德的作用被描述为“ *有着通过确立一定的善恶标准和行为准则，来约束人们的相互关系和个人行为，调节社会关系，并与法一起对社会生活的正常秩序起保障作用* ”。我对于道德的认识就是“群体或社会为了降低运行成本而出现的产物”，它可以是心照不宣的想法，也可以是成文的规矩和标语。拿我比较熟悉的编程来做个类比的话，道德就像是编程风格或是项目规范一样的东西，比如类型是否首字母大写，变量名采用下划线还是驼峰命名，括号是否要放到下一行，等等。现实中的道德要远比编程规范复杂，不过举个例子有助于理解。如果我们违反了编程规范，这样的后果可能是一段时间后就看不懂代码了或是团队成员的斥责，如果我们违反了道德，这样的后果可能是内心的愧疚或是他人的不认同。

关于道德的陈述就到这里了，我没有时间去深刻了解道德的起源以及进一步的伦理学知识，至于“道德是用来约束自己还是它人”，“道德绑架”，“道德制高点”，等问题或名词这里就不讨论了，我的认识止步于“道德是一种降低 *群体* *熵值* 的 *非强制* 性手段”。

上面我用了编程规范来类比道德，这里不妨用编程语言的标准来类比法律。相比于代码规范，语言标准要严格的多，如果我们的代码中出现了语法错误，编译器会报错并停止编译，解释器会停止执行，也许会抛出异常。不同的编程语言有不同的标准，这就像不同的国家有不同的法律；相同的语言有不同的实现，就像不同的法律行使机构同一法律的可以有不同理解；语言中标准未覆盖的行为称为 UB（Undefined Behaviour），这对应于法律中没有规定的规则...

但是这只是一种不严谨的类比而已，维基百科中的法律词条是这样描述的：

#+BEGIN_QUOTE
法律（英语：Law） 是一种由规则组成的体系，由国家的强制力保证实施，规范个人行为。法律是一系列的规则，通常需要经由一套制度来落实。但在不同的地方，法律体系会以不同的方式来阐述人们的法律权利与义务。其中一种区分的方式便是分为欧陆法系和英美法系两种。有些国家则会以他们的宗教法条为其法律的基础。

[[https://zh.wikipedia.org/wiki/%E6%B3%95%E5%BE%8B][法律 - 维基百科，自由的百科全书]]
#+END_QUOTE

上面这段话的重点应该在于： *由规则组成的体系，由国家的强制力保证实施，规范个人行为* 。相比于道德它具有强制性，违反法律的后果一般也比违反道德要更加严重。至于为什么要有法律，我的认识是：法律提供了一种 *解决冲突* 的方法，它给我们提供了强制性的行事规则。如果要我说说道德和法律的关系的话，我认为道德位于法律的上层。如果说法律是操作系统的话，道德就是操作系统之上的 APP。不知道你是否看到过这样的言论：如果一个人从来不冒犯女性，那么它一定对所有冒犯女性的方式了如指掌。但事实显然不是这样的，还有另外一种可能性：我不冒犯女性是因为我使用了更高的标准来要求自己。即使我是个法盲，在大多数情况下我也能遵守道德要求在社会上正常生活。

和道德一样，法律在我们的生活中是无处不在的，只是我们可能很少有需要对它进行了解。中国的法律体系由以下内容构成：

#+BEGIN_QUOTE
(a) 根本法：宪法及宪法相关法；

(b) 基本法：关系国家和社会生活基本问题的法律，包括行政法、民商法、经济法、社会法、刑法、诉讼及非诉讼程序法等；

(c) 基本法律之外的法律：在基本法基础上，对某一具体问题制订的法律，如公司法、知识产权法等；

(d) 规范文件：包括行政法规、地方性法规、部门及政府规章、民族自治地方的自治条例和单行条例等。

[[https://research.hktdc.com/sc/article/NDM1NzI4NjA4][中国法律制度简介 | 香港贸易发展局经贸研究]]
#+END_QUOTE

维基上还有个[[https://zh.wikipedia.org/zh-hans/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E6%B3%95%E5%BE%8B%E5%88%97%E8%A1%A8][中华人民共和国法律列表]]，由于实在是太多了这里就不一一列举了。本文中我们主要关注的就是民商法中的《[[http://www.npc.gov.cn/npc/c30834/202011/848e73f58d4e4c5b82f69d25d46048c6.shtml][著作权法]]》、《[[http://www.npc.gov.cn/npc/c30834/201905/dacf65eec798444e821a1e06a347f3ee.shtml][商标法]]》和《[[http://www.npc.gov.cn/npc/c30834/202011/82354d98e70947c09dbc5e4eeb78bdf3.shtml][专利法]]》三者构成的《[[http://xxgk.beihai.gov.cn/bhstjj/zcfgzl_84913/zcfg_88758/201905/t20190517_1878596.html][知识产权法]]》。

这里简单做个总结吧，就我来看的话，道德和法律都是化解冲突，减小社会运行成本的手段，但是道德不具有强制性，一般通过倡导或劝诫进行；而法律是由国家强制保证实施的规则，它被用来解决更加激烈的冲突。就像语言的引入也许是为了人类能够更好的进行思考，道德和法律的引入也许是为了社会能更好的运行，也许这应该是十分自然的。

** 什么是权利

/注意这里是权利（rights）而不是权力（power），不过我们也可以顺带了解一下权力/

#+BEGIN_QUOTE
【暴力】：①强制的力量。②特指国家的强制力量。

【权力】：①政治上的强大力量。②职责范围内的支配力量。

【权利】：公民或法人依法行使的权力和享受的利益（跟“义务”相对）。

【义务】：公民或法人按照法律规定应尽的责任，例如服兵役（跟“权利”相对）。

【法律】：由立法机关或国家机关制定，国家政权保证执行的行为规则和总和。包括宪法、基本法律、普通法律、行政法规和地方性法规等规范性文件。法律体现统治阶级的意志，是阶级通知或阶级专政的工具。

【法人】：法律上指根据法定程序设立，有一定的组织机构和独立的财产，参加民事活动的社会组织，如公司、社团等。法人独立享有与其业务相关的民事权利，承担相应的民事义务（区别于“自然人”）。

【自然人】：①指基于自然规律而产生的一切具有生命形式的人。②法律上指在民事上能享受权利并承担相应义务的个人（区别于“法人”）。
#+END_QUOTE

字典中将权利定义为“依法行使的 *权力* 和享受的 *利益* ”，维基百科的权利词条给出了另一种说法，除了维基百科外我也找到了一些其他的资料：

#+BEGIN_QUOTE
权利是近代由英语中的“right”和德语中的“Recht”一词翻译而来。1864年美国传教士丁韪良在翻译惠顿的《万国公法》时使用了“权利”一词，后在日本也开始使用这个译名，包括西周及法学家箕作麟祥的译本，其中，箕作麟祥的译本传回中国，影响了在中国的用法。但是，中文语境中的“权利”和“right”这个词原本的意思不合。英语“right”的本义是正当、合理、合法、合乎道德的东西，比如生存、生育、受教育、宗教信仰自由等，而并非权力和利益（英语：jurisdiction and benefit）含义的复合，也不意味着任何牟取利益的权力。

[[https://zh.wikipedia.org/zh-cn/%E6%9D%83%E5%88%A9][权利 - 维基百科，自由的百科全书]]

权利是指主体依法享有并受法律保护的利益范围或实施一定行为以实现某种利益的资格，是法律赋予人实现其利益的一种力量。

[[https://wiki.mbalib.com/wiki/%E6%9D%83%E5%88%A9][权利 - MBA智库百科]]

Rights are legal, social, or ethical principles of freedom or entitlement; that is, rights are the fundamental normative rules
about what is allowed of people or owed to people according to some legal system, social convention, or ethical theory.
Rights are of essential importance in such disciplines as law and ethics, especially theories of justice and deontology.

[[https://en.wikipedia.org/wiki/Rights][Rights - Wikipedia]]
#+END_QUOTE

从以上内容可以看到，不论是将权利理解为“权力和利益”，“实现利益的资格”，还是 /fundamental normative rules/ ，它们都需要法律的支持和保护。不管是权利还是义务都是法律术语，属于法律这个“操作系统”的一部分。我们之所以需要它们，可能是用起操作系统比裸机还是舒服太多（笑）。

“权利和义务是一对有机的整体”，“权利和义务是统一的”，相信这样的话我们从小到大也听过不少了，法律在规定了我们享有的权利时也规定了我们应该应尽的义务。从维持系统 *稳定* 的角度来看，法律规定与权利对应的义务是很好理解的，它可以限制权利的范围，在保障权利的行使时不会损害他人或社会的利益。话虽如此，不存在与之对应义务的权利和不存在与之对应权利的义务想必也是存在的，但这种情况下对应权利或义务的缺失应该不会有明显的缺陷。用大白话来说的话，也许权利就是“我在不犯法的情况下能干什么”，义务就是“法律要我干什么”。

以上就是现在的我对权利的全部认识了，我会在下一节中对知识产权的具体内容做一些介绍，这一节的目的还是补充一些背景知识。

** 什么是知识产权

有了对法律和权利的简单的认识，从知识产权这个名字我们也可以猜出个七七八八。既然是知识产权，那应该是知识创造者拥有的权利，与知识产权相对应的应该是知识产权法。实际上也没差多少：

#+BEGIN_QUOTE
知识产权（英语：intellectual property），是人类用智慧创造出来的无形的财产，主要涉及著作权、专利、商标等领域。音乐和文学等形式的艺术作品，以及一些发现、发明、词语、词组、符号、设计都能被当作知识财产而受到保护。知识产权可以分为工业产权与版权两类，工业产权包括发明（专利）、商标、工业外观设计和地理标志，版权则包括文学和艺术作品等。

- 工业所有权，它包括发明（专利）、商标、工业品外观设计以及原产地地理标志等。专利保护期一般20年，工业设计保护至少10年，而商标则可无限期保护。

- 著作权，它包括文学和艺术作品：诸如小说、诗歌和戏剧、电影、音乐作品；艺术作品诸如绘图、绘画、摄影和雕塑以及建筑设计。与著作权相关的权利包括表演艺术家对其表演的权利、录音制品制作者对其录音制品的权利以及广播电视组织对其广播和电视节目的权利。著作权持续到作者逝世后至少50年。

- 此外还有一种特殊的知识产权：商业秘密。企业可以认定任何信息为“商业秘密”，禁止能够接触这些机密的人将秘密透露出去，一般是透过合约的形式来达到这种目的。只要接触到这些秘密的人在获取这些机密前签署合约或同意保密，他们就必须守约。商业秘密的好处是没有时限，而且任何东西都可被认定为商业秘密。例如可口可乐的配方就属商业秘密，100多年来外界都无法获知可口可乐的全部成分。

[[https://zh.wikipedia.org/wiki/%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83][知识产权 - 维基百科，自由的百科全书]]
#+END_QUOTE

至于知识产权法的作用，这里我就直接摘抄《中华人民共和国知识产权法》的第一章第一条：

#+BEGIN_QUOTE
第一条 为保护文学、艺术和科学作品作者的著作权，以及与著作权有关的权益，鼓励有益于社会主义精神文明、物质文明建设的作品的创作和传播，促进社会主义文化和科学事业的发展与繁荣，根据宪法制定本法。
#+END_QUOTE

从内容上看，知识产权法是为了 *保护著作权等相关权益* ， *鼓励有价值作品的创作和传播* ， *促进社会的发展和繁荣* 。这应该可以作为这一节的答案了，它同时保护创造者和整个社会的利益（ *最终是为了社会* (不如说所有的法律理论上都是为了社会服务的)）。 +至于它是通过什么做到的，我会在下一节对它的内容做简单介绍来尝试说明。+

#+BEGIN_QUOTE
无论是技术方案还是作品，本质都是一种信息。John Perry Barlow 在其著名的《思想的经济学》(The Economy of Ideas') 一文中曾经指出：信息是自由的(Information wants to be free)。信息的本质决定了它天然能够自由流动。信息一旦被传播出去，人们就可以轻易地进行复制和再传播。这就是指南针在古代被无数工匠自由复制的原因。既然信息是“自由”的，那么提供这一信息的人一旦传播了信息，就无法依靠自己的力量对信息进行排他性的控制，由这一信息所表达的智力成果就不可能成为法律意义上信息创造者的财产。

而法律之所以要将“自由”的信息转变为属于创造者的财产，是出于实现特定公共政策的需要。在近代欧洲，科学技术在经济发展和社会进步中的极端重要性已经日益显现,同时各国之间人才流动又越来越频繁。如果一国不通过法律强制性地将发明创造成果规定为创造者在法律上的财产，仍然听任其“自由”地被他人仿制、使用，发明人就无法从发明创造成果中获得报酬，等于是将其聪明才智无偿地贡献了出去。这样一来，一方面，不会有很多人愿意进行可能具有巨大社会利益和经济价值的发明创造；另一方面，可能导致大量人才离开本国。因此，法律需要通过赋予发明人对其发明创造的财产权来换取他们投身于发明创造活动的积极性，在使自己享有财产权的同时造福国家。

作品从自由传播的信息演变为由作者享有的财产，同样是法律创设著作权这一新型财产权的结果。作者创作作品往往需要付出极大的心血和创造性劳动，而造纸术和印刷术使作品的复制和传播极为容易。如果不强制性地将作品界定为作者的法律意义上的财产，使 作者能够从作品中获得合理的报酬，就难以繁荣文艺创作。由此著作权法应运而生，创设了一系列由作者享有的专有权利，以控制复制、发行、公开表演等对作品的特定使用行为,以此保障作者能够从其创作中获得经济利益，从而鼓励更多的人投身于文艺创作。而此后复制和传播技术的每一次巨大进步，都会引起著作权法相应的变革，著作权法会规定新的专有权利或扩张原有专有权利的控制范围加以应对。因此，著作权法的发展历史，就是著作权这种特殊的财产权随着复制和传播技术的发展而不断扩张的历史。

《知识产权发教程(第七版)》 第一章 总论 第一节 —— 王迁
#+END_QUOTE

/原本我打算在下一节简单介绍一下知识产权法的内容，不过由于我没有法律专业知识，这样的介绍并不专业，反倒可能误导读者，遂推荐一本书：《知识产权发教程(第七版)》 王迁。对于我这种小打小闹的创作来说，我更需要的可能是具体该做和不该做什么，而不是一个完善的法律框架。/

* 一些和创作相关的词汇

在这一节中，我会介绍一些和创作相关的行为，算是对基础知识的说明（我在查阅资料之前对此几乎一无所知）。

** 抄袭（Plagiarism）

抄袭也叫剽窃，指抄录他人作品为己作，对于原著未经修改。

#+BEGIN_QUOTE
有时抄袭的认定较难以做出客观判断，必须经过主观判断，例如模仿一个故事的情节是否属抄袭就有很大争议，一些人认为故事情节属于思想范围，而“抄袭思想”并不是侵权的行为，因为法律只保护思想的表现方式，而不是思想本身。有些抄袭行为虽未达到客观上的侵犯权利，但是在学术界或相关领域，则是严重的违背道德良知行为。不当的抄袭行为，可能导致学位、褒是认证的撤销，严重者恐面临法律诉讼及求偿。

[[https://zh.wikipedia.org/zh-cn/%E6%8A%84%E8%A2%AD][抄袭 - 维基百科，自由的百科全书]]
#+END_QUOTE

在我看来抄袭是不道德的，我在写东西的时候碰到别人写过但我正好用得上的的东西，我都会尽可能给出原始内容的来源。

另外，抄袭当然是违法行为，不过对抄袭的判定似乎不是那么容易，比如并不完全照搬，而是在原有内容的基础上调整语序和语意，这样的行为似乎叫做“洗稿”。

** 引用（Quote, cite）和参考

#+BEGIN_QUOTE
*第二十四条* 在下列情况下使用作品，可以不经著作权人许可，不向其支付报酬，但应当指明作者姓名或者名称、作品名称，并且不得影响该作品的正常使用，也不得不合理地损害著作权人的合法权益：

（二）为介绍、评论某一作品或者说明某一问题，在作品中适当引用他人已经发表的作品；

（三）为报道新闻，在报纸、期刊、广播电台、电视台等媒体中不可避免地再现或者引用已经发表的作品；

《中华人民共和国著作权法》
#+END_QUOTE

根据这条法规来看的话，只要是合理的引用是不会对作者造成损害的。我们在使用他人内容时也要注意出处和内容的准确性。

值得一说的是这是针对文字的，插图好像没有引用的概念，难道我们要截取一部分放到自己的作品中吗（笑）。

** 原创（Originality）和二创

#+BEGIN_QUOTE
独创性或原创性（英语：Originality）泛指作品是全新的，而不是经由复制、改编、剽窃、模仿、抄袭、二次创作，或系列作的衍生作品。新发明的物品可称之为原创物。

[[https://zh.wikipedia.org/zh-cn/%E7%8D%A8%E5%89%B5%E6%80%A7][独创性 - 维基百科，自由的百科全书]]
#+END_QUOTe

我认为把“原创”理解为“完全凭自己创作出来的作品”即可。二次创作则是在原创（或者是其他二次创作）的基础上的再创作，相比于剽窃还是抄袭，它的区别还是挺明显的，二次创作一般都会明确以某作品来进行改编或发展，比如关于基于东方 project 的视频创作在开头大多会有二次创作声明。

关于二次创作相关的说明，我觉得萌娘百科的词条写的最好：

#+BEGIN_QUOTE
二次创作（英语：re-creation）是指使用了已存在著作物的文字、图像、影片、音乐或其他艺术作品创作的行为。而这些作品则称为“二次创作物 (Derivative work)”。

是与“独创”相对的概念。

[[https://zh.moegirl.org.cn/zh-hans/%E4%BA%8C%E6%AC%A1%E5%88%9B%E4%BD%9C][二次创作 - 萌娘百科 万物皆可萌的百科全书]]
#+END_QUOTE

在 CC 协议中有一个演绎（Derivative）的概念，应该和二次创作相近。

** 翻译（Translation）

#+BEGIN_QUOTE
*第十条* 著作权包括下列人身权和财产权：

（十五）翻译权，即将作品从一种语言文字转换成另一种语言文字的权利；

*第十三条* 改编、翻译、注释、整理已有作品而产生的作品，其著作权由改编、翻译、注释、整理人享有，但行使著作权时不得侵犯原作品的著作权。

《中华人民共和国著作权法》
#+END_QUOTE

这也就是说在没有经过作者允许的情况下翻译他的作品是构成侵权的。我之前大段翻译过微软的 Win32 文档，不过微软也懒得管我就是了（笑）。

** 转载（Reproduce）与分享（Share）

所谓转载指的就是把他人的作品重新发布，分享指的是将原内容的链接发送给其他人。拿编程打个比方的话，前者是深拷贝，后者是浅拷贝。

我对转载这个词第一次被我了解到的情景没啥印象了，不过可能是来自“無断転載禁止”（むだんてんさい）。所谓无断转载是指“未经原作者文件或口头同意的情况下，擅自将其作品转载到他处的行为”（[[https://otomad.wiki/%E6%97%A0%E6%96%AD%E8%BD%AC%E8%BD%BD][OtomadWiki]]），我在我之前的文章中使用了很多来自 Pixiv 的图片作为封面或文章结尾的贴图，根据这个定义来看这就属于是无断转载，侵犯了原作者的权利了。

#+BEGIN_QUOTE
在互联网上，视频、音频、图像、文字都有其最初的创作者，对此类内容的搬运，是需要获得创作者的授权和肯定的。

由于中国大陆的互联网发展起步较晚，著作权相关的条文尤其是互联网著作权和对侵权行为的制止尚不完善，在无断转载过于普遍、无法有效举证和疏通、绝大部分没有造成实质性损害等等原因下，原作者极少去进行制止，使得前二十年的各种互联网侵权行为在国内被忽视和默许。

随着网民权利意识的进步，在从其他地方获取信息的时候，越来越需要注重著作权的重要性。避免侵权的方式包括转载取得授权、不对内容加以施工、不以此牟利、不大范围扩散等。

[[https://otomad.wiki/%E6%97%A0%E6%96%AD%E8%BD%AC%E8%BD%BD][无断转载 - 中文音MAD维基 OtomadWiki - 音MAD的百科全书 (｡･∀･)ﾉﾞ]]
#+END_QUOTE

我在贴出封面图片时总是会给出原始链接，但是我从来没有和作者联系过，不知道算不算“半无断转载”（笑），不过实际上还是侵权行为。在文本完成后我应该会移除掉嵌入到文章中的图片，而保留原始链接，这样就从无断转载变成了分享。如果我想要在我的文章中嵌入图片的话，我需要与原作者联系并获得许可，这样比较费事，也许直接放个链接在文章的开头更好。如果能联系上作者并获得许可，就我个人来说当然是更好，技术文章是需要除了代码高亮的一点色彩的。

* 代码公共许可证

/虽说对于利用作品这个目的来说这一节看上去有点多余，不过因为我的文章中时不时要用到一些代码，不如顺带了解一下吧/

如果你玩过 github，你应该对各种开源许可证（Open Source License）不会很陌生，比如 GPL，MIT，Apache，BSD，WTFPL 等等。这一节的目的在于介绍开源许可证的作用，以及一些常见的许可证。在 GNU 官网的这个[[https://www.gnu.org/licenses/license-list.zh-cn.html][页面]]中列举了数百种许可证，其中的大部分你应该都没听说过。

就像文章一样，代码也是有版权的（我第一次了解到时居然感觉很不可思议）。当我们发现一段代码或一个项目对个人项目有作用时，我们可能会想要使用别人的已经测试好的代码而不是自己写一份，要使用别人的代码我们就必须获得他人的许可，一般来说这比较麻烦，但随意使用他人的代码又是违法的。如果代码或项目指定了某种许可证，我们就能够在满足许可证要求的情况下使用他人的代码而无序请求授权，这样无断转载就完全不存在了，因为我使用你的东西而不需要你亲自许可。

我没有找到关于使用代码公共许可证的好处的权威说明，不过我们很容易想到，这样的许可证是有利于代码的传播和知识流通的。

** GPL（GNU Public License）

要想了解协议的内容，最直接的方法是把整个协议读一遍：[[https://www.gnu.org/licenses/gpl-3.0.html][GPL 3.0]]。虽然我不是太想读，但是了解一下也没有什么坏处，下面我会对许可证中的突出内容进行引用和解释：

#+BEGIN_QUOTE
By contrast, the GNU General Public License is intended to guarantee your freedom to share and change
all versions of a program--to make sure it remains free software for all its users.
#+END_QUOTE

GNU 许可证用来保证你分享和修改某个程序所有版本的自由 —— 让它对所有的使用者总是一个自由软件。

#+BEGIN_QUOTE
When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are
designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish),
that you receive source code or can get it if you want it, that you can change the software or use pieces of it
in new free programs, and that you know you can do these things.
#+END_QUOTE

当我们谈到自由软件时，我们指的是自由，而不是价格。我们的许可证旨在确保你有分发自由软件副本的自由（如果你愿意，还可以收费），你能够获得源代码，你能够修改软件或是将它的片段用在新的自由软件中，而且你知道你可以做这些事情。

#+BEGIN_QUOTE
Developers that use the GNU GPL protect your rights with two steps: (1) assert copyright on the software,
and (2) offer you this License giving you legal permission to copy, distribute and/or modify it.
#+END_QUOTE

使用 GPL 的开发者可以通过这两个步骤保护你的权利：（1）声明软件的版权（2）向你提供本许可证，给予你复制、分发和/或修改软件的法律许可。

读到这里我发现我读不下去了（笑），不然就到这里吧。github 提供了一个帮你挑选 LICENSE 的[[https://choosealicense.com/][网站]]，这是它的 GPL [[https://choosealicense.com/licenses/gpl-3.0/][页面]]。GNU 官网上也有对 GPL 3.0 的[[https://www.gnu.org/licenses/quick-guide-gplv3.html][说明]]。由于法律知识的欠缺，我对 GPL 3.0 原文的了解就到此为止了。网络上有许多对于 GPL 的讨论，鉴于我对这个许可证还是不够了解，这一小节就到这里了。

我在 github 上发布的代码对于许可证的选择比较随便，GPL，MIT，BSD，WTFPL 都用过，但我并没有很严肃地使用过代码许可证，毕竟都是些玩具代码。等到真正做什么大项目时，也许我会对许可证的选择进行认真的考虑（应该不太可能会有这种时候）。

* 知识共享许可协议（CC）

/我之前在个人博客上使用的是 CC-BY 4.0，但我一直不知道它的含义。这一节中我会对其中的一些协议做简单的介绍/

如果你经常逛一些维基站的话，你会发现它们可能会使用 CC 协议，比如维基百科的 [[https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC][CC BY-SA 3.0]]，萌娘百科的 CC BY-SA 3.0 CN。这里的 CC 是 Creative Commons（共享创意）的缩写，它是一个国际性的非盈利组织，旨在让人民能够发展和维持繁荣的共享知识和文化的公域。CC 协议是一种由共享创意发布的协议，根据维基百科的描述，它的内容如下：

#+BEGIN_QUOTE
知识共享许可协议（英语：Creative Commons license，或创用 CC 授权）是一种公共版权授权条款，其允许按照多种需求分发受版权保护的作品。一个作者可使用创作共用授权授予他人分享、使用，甚至创作衍生作品的权利。创作共用提供给作者灵活性（例如，他们可以选择允许非商业用途使用他们的作品），保护使用或重新分配他人作品的人，所以他们只要遵守由作者指定的条件，而不必担心侵犯版权。

知识共享许可协议有多种不同类型。许可证可以有不同的组合，并由分发条款决定。

[[https://zh.wikipedia.org/zh-hans/%E7%9F%A5%E8%AF%86%E5%85%B1%E4%BA%AB%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE][知识共享许可协议]]
#+END_QUOTE

和代码许可证类似，一旦我们看到了 CC 协议，我们就能在遵守协议的前提下直接使用作品而无需与作者联系。这对于我们使用他人作品来说是很方便的。对于许可协议的作用，在 CC 官网上有很详细的[[https://creativecommons.org/licenses/?lang=zh][说明]]，这里我就不说了。协议内容似乎也没什么好说的，对我来说直接用 CC BY 或 CC BY-SA 就行了。

* 那么，我该怎么做呢

- 不要抄袭
- 对于引用的内容，尽可能给出来源
- 对于使用版权的内容，尽可能获取作者的许可
- 尽可能多地使用 CC 授权的作品
