#+SETUPFILE: ../setup.org
#+FILETAGS: blog
#+TITLE: 怎么弄一个自己的 blog —— 怎么感觉方向弄错了捏
#+DATE: [2023-01-12 Thu 22:57]

{{{begin_noscript}}}
#+NAME: headimg
#+ATTR_HTML: :class top-down-img
[[https://www.pixiv.net/artworks/104273741][file:0.jpg]]
{{{end_noscript}}}

按照 LAMP 的顺序的话这篇文章应该介绍 Linux 下 PHP 的安装和使用，但写着写着我突然发现有点不对劲，我到底是来学 LAMP 来了还是学搭博客来了？

我原本的想法是首先介绍最基本的 HTTP 服务器基本环境的搭建，然后在此基础上介绍 wordpress 的安装和使用，然后一转 nodejs，使用 node 实现简单的服务器。接着在此基础上介绍博客应该具有的功能和特性，然后介绍一些静态博客工具的使用。最后，我们来看看一些不错的博客，在有所借鉴后完成整个博客的搭建。分个步骤的话大概是这样：

- 如何搭建简单的 HTTP 服务器
- 如何使用静态网站生成工具
- 如何设计博客外观和功能

整个过程大致是从地基到骨架再到外观，看上去还挺有序的不是吗？把整个过程走完应该能学到不少。但我在做的过程中也在不断地发现新东西，然后发现好像白忙活了一场......就 HTTP 服务搭建来说，我们完全可以直接使用 github-pages 或者 cloudflare pages，或者使用容器，而不是搁这全部手动做一遍。静态网站生成的话，网上也已经有了无数的文章教你怎么使用各种各样的东西，比如 Hugo，Hexo，Jekyll 等工具。至于博客外观和功能就更不用我在这好为人师了，wordpress 有成千上万种主题供人选择，鼠标点几下就能装上，其他的应该也差不多，这还有必要自己糊 CSS 吗？

一言以蔽之，搭建博客所需要的东西你都能找到现成的，自己从头开始弄起就是纯纯的浪费时间。就算我从头到尾把这些东西摆弄了一遍，我也只是在众多折腾文章的基础上写了一篇时间比较新的而已。与其把别人修过的路再修一遍，不如直接走过去来的方便。

如果我之后还会写以“怎么弄一个自己的 blog”为题的文章，那要么是弄完之后的成果展示，要么是我找到了新的可折腾的东西，比如给 org-mode 的 export 写一个 ox 包啥的。接下来要做的事大概就是照着做的不错的博客随便弄个自己的出来。 *博客的重点还是应该在写了什么东西上* ，而不是说要多好看。

新年快乐。
